services:
  web:
    build: .
    command: bash -c "bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/myapp2
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp2_development
  